name: Build and Syntax check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4 #command used in GitHub to checkout repository
    #set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: '8.0'        

    # Restore any dependencies
    - name: Dependencies
      run: dotnet restore


    #Run any unit tests
    - name: Unit Test
      run: dotnet test

    #Build the project 
    - name: Project Build
      run: dotnet build --configuration release
